### ISSUE TITLE
running on multiple samples

### ISSUE THREAD

**Issue by isadeghi87** [theislab/hadge#42]
Hi,
How would be the command or input parameters when running on multiple samples. It is just mentioned that a samplesheet is needed but it's not specified how would be the parameters.
Plus, is it possible to run all genetic method at the same time for multiple samples? if so, how?

Tnx
Iman

**Comment by isadeghi87** [comment]
@Zethson

**Comment by bio-la** [comment]
Hey @isadeghi87 thanks for using our tool. We are in the process of adding more documentation and we agree that the multisample option is one of the most useful ones. 
we provide an example sheet [here](https://github.com/theislab/hadge/blob/main/test_data/multi_sample_input.csv) (in general the parameters for the methods are specified in the workflow configuration file, and by default all the methods are run.
@wxicu i believe would be useful to link the file that @maxozo prepared for the Onek1k dataset (masking the sensitive paths) to give a good example of multisample parallel processing.
thank you!

**Comment by isadeghi87** [comment]
@bio-la any ideas?

**Comment by wxicu** [comment]
Hi @isadeghi87 to run the genetic mode with multi samples without hashing input, you need to specify:

- in the sample sheet: all the hashing input parameters including  `hto_matrix_raw`, and `hto_matrix_filtered` to None. Alternatively, you can also set `rna_matrix_raw`, `rna_matrix_filtered` to None.
- Run the command nextflow run main.nf --multi_input $samples --outdir $outdir --fasta $fasta --fasta_index $fasta_index --mode genetic --max_cpus 30 --max_memory 200.GB -bg **--generate_anndata  False --common_variants_cellsnp ${vcf_donor} --match_donor False**
- short explanation: if you dont provide any rna count matrices, then the anndata generation should be disabled. Also, since you have donor genotype, you can skip the donor matching process. You can use the donor genotype for cellsnp to generate the input for vireo. 
Hope this helps and thanks for using hadge!

**Comment by wxicu** [comment]
Please feel free to reopen this issue if you are still running into issues and we would be happy to help troubleshoot further.
