### ISSUE TITLE
Souporcell fails due to bcftools not found

### ISSUE THREAD

**Issue by bednarsky** [theislab/hadge#49]
Hi! 

I am running the newest version of the pipeline on some more samples and encountered a new error: 
> ERROR ~ Error executing process > 'HADGE:run_multi:gene_demultiplexing:demultiplex_souporcell:souporcell (sample_name)'
> 
> Caused by:
>   Process `HADGE:run_multi:gene_demultiplexing:demultiplex_souporcell:souporcell (sample_name)` terminated with an error exit status (127)
> 
> Command executed:
> 
>   bcftools view path/to/projects/results/demultiplexing/split_wgs_vcf/sample_name.vcf -Ov -o unzipped.vcf
> 
>          mkdir souporcell_sample_name
>          mkdir souporcell_sample_name/souporcell_out
>          touch souporcell_sample_name/params.csv
>          echo -e "Argument,Value
>   bamfile,sample_name__filtered_bam_file.bam
>   barcode,barcodes.tsv.gz
>   fasta,genome.fa
>   threads,5
>   clusters,2
>   ploidy,2
>   min_alt,10
>   min_ref,10
>   max_loci,2048
>   restarts,None
>   common_variant,No common variants are given.
>   known_genotype,path/to/projects/results/demultiplexing/split_wgs_vcf/sample_name.vcf
>   known_genotype_sample,No known sample names are given.
>   skip_remap,True
>   ignore,False " >> souporcell_sample_name/params.csv
> 
>          souporcell_pipeline.py --threads 32 -i sample_name__filtered_bam_file.bam -b barcodes.tsv.gz -f genome.fa -t 5 -k 2 --ploidy 2 --min_alt 10 --min_ref 10 --max_loci 2048 --known_genotypes unzipped.vcf  --skip_remap True  -o souporcell_sample_name/souporcell_out
> 
> Command exit status:
>   127
> 
> Command output:
>   (empty)
> 
> Command error:
>   .command.sh: line 2: bcftools: command not found

I think this might be because the container in the singularity process does not contain bcftools, but not sure
```nextflow
process souporcell{
    ...
    container "shub://wheaton5/souporcell"
    ...
```

**Comment by bednarsky** [comment]
Quickfix directly installing the module in the script (with our local module system) solved the issue. Of course not sustainable.

**Comment by wxicu** [comment]
> Quickfix directly installing the module in the script (with our local module system) solved the issue. Of course not sustainable.

Hi, 
the souporcell singularity container contains indeed bcftools (check [this](https://github.com/wheaton5/souporcell/blob/af738b98ac6e0b272b1cd6765b743d67e77d5527/Singularity#L83)). And I am also able to call bcftools within the container with `singularity run shub://wheaton5/souporcell`. I guess the possible reason here is that the cached container is not completely downloaded, maybe interrupted due to the previous process. You can try with `singularity clean cache` and restart the process.

Furthermore, we are now trying to get souporcell into bioconda ([PR](url)). Hope this will be merged soon!

**Comment by bednarsky** [comment]
Worked when adding `-profile cluster,conda_singularity`, as you proposed in https://github.com/theislab/hadge/issues/53
